### ISSUE TITLE
[1.20.1] Crash on loading Undergarden dimension

### ISSUE THREAD

**Issue by Fraali** [quek04/The-Undergarden#172] opened 2023-07-01 00:23 UTC
Using All The Mods 9, Minecraft version 1.20.1

Crash on loading the `Undergarden` dimension (Walking through the portal) with

`The game crashed whilst exception ticking world
Error: java.lang.IllegalAccessError: class quek.undergarden.entity.animal.Scintling tried to access private field net.minecraft.world.entity.Entity.f_19793_ (quek.undergarden.entity.animal.Scintling is in module undergarden@0.8.5 of loader 'TRANSFORMER' @77cd235b; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @77cd235b)`

**Comment by GoldenKnight175** [comment] 2023-07-01 01:36
Using All The Mods 9, Minecraft version 1.20.1
We are using Forge 47.0.34 
Not sure if this is the cause but it crashes while loading into the **Undergarden** dimension


The game crashed whilst exception ticking world 
Error: java.lang.IllegalAccessError: class
quek.undergarden.entity.animal.Gloomper tried to access
private field net.minecraft.world.entity.Entity.f_19793_
(quek.undergarden.entity.animal.Gloomper is in module
undergarden@0.8.5 of loader 'TRANSFORMER' @6630dd28;
net.minecraft.world.entity.Entity is in module
minecraft@1.20.1 of loader 'TRANSFORMER' @6630dd28

**Comment by GizmoTheMoonPig** [comment] 2023-07-01 01:40
Yeah it's the same kind of crash. I'll fix this as soon as I can, currently not home

**Comment by bconlon1** [comment] 2023-07-01 01:45
Issue appears to have started with a change from Forge as of 47.0.26; https://github.com/MinecraftForge/MinecraftForge/pull/9583 (https://github.com/MinecraftForge/MinecraftForge/pull/9583/files#diff-3c5e61e6b3303cd31e5882573871953441b3b1d9a4cc7b018b1ff5eda25ce27dL222)

**Comment by GizmoTheMoonPig** [comment] 2023-07-01 06:03
fixed in ab85ba5

**Closed as completed by GizmoTheMoonPig** 2023-07-01 06:03 UTC
