### ISSUE TITLE
Data pack error

### ISSUE THREAD

**Issue by LegendDerp** [quek04/The-Undergarden#55] opened 2021-01-02 15:51 UTC
Hello, I faced an issue while updating the mod from 0.3.8 version to 0.4.0
I am on "Optimum Modpack" https://www.curseforge.com/minecraft/modpacks/optimum-modpack
In this world I have never been to The Undergarden so the dimension has never been generated.
When I update the mod, I face no crashes and I am able to join the world with no problems. But, if I save & quit the world and try to join again, I face this issue.
Downgrading the mod to 0.3.8 seems to fix this issue.
I would like to play with the updated version of the mod in the future with the world I have created so I hope there is a solution.
Choosing the Safe option doesn't do anything.
From what I can see, in saves folder, datapacks folder is empty in both preupdated and updated versions.

I also tried updating, then going into the world, going to undergarden which worked, save & quit. But again, I couldn't join the world again and received same message

![error](https://user-images.githubusercontent.com/73384328/103460914-5e8a8180-4d2b-11eb-9a0f-e0d16e7afa9c.png)

**Comment by LegendDerp** [comment] 2021-01-02 15:55
Here is the latest log which I tried the last thing I mentioned
[latest.log](https://github.com/quek04/The-Undergarden/files/5760468/latest.log)

**Comment by quek04** [comment] 2021-01-02 17:48
none of the errors in your log mention the undergarden

**Comment by LegendDerp** [comment] 2021-01-02 17:59
I know but, this issue only happens when I update the Undergarden mod from 0.3.8 to 0.4.0
I also looked through the logs but couldn't figure out any solutions

**Comment by quek04** [comment] 2021-01-02 17:59
are you loading a world made with undergarden 0.3.8?
0.4.0 introduces a new biome and structure, that might've broke something?

**Comment by quek04** [comment] 2021-01-02 18:00
there are errors that mention a failure to save level.dat files

**Comment by LegendDerp** [comment] 2021-01-02 18:01
Correct, I first created my world with 0.3.8 version. I never generated the undergarden dimension though

**Comment by LegendDerp** [comment] 2021-01-02 18:01
I was hoping if there was a way to update to 0.4.0 without creating a new world

**Comment by drakray** [comment] 2021-01-02 18:31
Just FYI, I got this same bug even before 0.3.8, so it might not be cause by 0.4.0, or even by Undergarden for all I know, but there IS something fishy somewhere. Datapack is just a bad idea IMO, but I'm just a user, so ¯\_(ツ)_/¯
Might even be a Forge trouble, since most of the recent update where about Biome and BiomeRegistry, which seems to glitch with Datapack Biome, as seem with the recently discovered trouble with Aquaculture.

**Comment by quek04** [comment] 2021-01-02 18:32
i don't know how to make dimensions/biomes in 1.16 without a datapack, so

**Comment by drakray** [comment] 2021-01-02 18:38
Well that's a bummer lol XD
The only other mod I use that create a new dimension is Rats/Ratlantis, and I dont even know if THEY use Forge to make theirs(though I suspect they Datapack too, as the folder structure would imply)
Maybe LostCities, I dunno..., I only modded slightly in 1.12 to get a general idea of how things work, but real life took precedance :/
You could maybe look if there is a way to make dimension/biome with datapack, but register them in Forge at the same time?, I don't know the state of documentation/help in the current Forge :'(

I'll try to "get in a world, go out and in again" without Undergarden to see if it's the source of this trouble, or at least part of the conflict.

**Comment by quek04** [comment] 2021-01-02 18:39
current forge has 0 documentation

**Comment by drakray** [comment] 2021-01-02 18:40
Still, do not get discouraged, your mod is very nice and well done, we'll find some info to get through this XD

Right, cause that's helping.... :/
This MIGHT be part of why Fabric is so popular lately :/ lol..

**Comment by drakray** [comment] 2021-01-02 19:17
Ok so, I remove Undergarden, stil got the same trouble. Also, when starting a solo world, it flashes back to main menu after loading the world before entering the world.
I then removed Ratlantis and Woot, both of which add Datapack Dimension, and the "flash to menu" seems gone, but I still got the "errors in currently selected datapack".
Also, when trying /reload before exiting, I got
```
[02Jan2021 14:11:14.030] [Server thread/WARN] [net.minecraft.command.impl.ReloadCommand/]: Failed to execute reload
java.util.concurrent.CompletionException: java.lang.IllegalStateException: Duplicate key net.minecraft.tags.Tag@24bb4afa
```

in debug.log, which is another trouble with datapack -_-
At least the datapack dimension/biomes don't seems to be in cause here, so that's that \o/
Small victories people, small victories lol XD

**Comment by drakray** [comment] 2021-01-02 20:04
Reenabling UG, Rats and Woot, disabling Ice&Fire:
The "flash to menu", logged as 
```
[Render thread/WARN] [net.minecraft.client.Minecraft/]: Failed to read level World123 data
java.io.IOException: The process cannot access the file because another process has locked a portion of the file
```
is back, but the /reload command worked, and exiting and going back in the world is... not working, but at least clicking on Singleplayer is working.
Trying to go in another World is... very long, but not working, WITHOUT the "errors in currently selected datapack", at least

**Comment by drakray** [comment] 2021-01-02 20:10
After all, I think it's safe to say that this specific bug is not caused by Undergarden, Blame find no error from it, and when searching for Undergarden in the log, then refining to search for ERROR, I find nothing, so other than the weird thing with Aquaculture, I'd say it's a win \o/, and we could close this specific issue

**Comment by LegendDerp** [comment] 2021-01-02 20:15
I see, interesting. I wonder if those other mods will face the same issue when they update. I guess i will just put a notice at my modpack and say "You can update The Undergarden mod only before creating a world" till further notice

**Closed as completed** 2021-01-02 20:15 UTC

**Comment by drakray** [comment] 2021-01-02 20:17
Well this error is only visible if you save&quit and try to go in a world before restarting the game, it is not related to version, nor to Undergarden itself

**Comment by LegendDerp** [comment] 2021-01-02 20:20
Yeah, currently I have only faced this issue with this mod and my modpack currently only misses Undergarden update so, I figured a notice would be required
