### ISSUE TITLE
Additional portals getting generated close to eachother when players go through.

### ISSUE THREAD

**Issue by SodiumShine** [quek04/The-Undergarden#83] opened 2021-02-21 00:49 UTC
It doesn't happen every time and I can't be sure what causes it. There are also other portals nearby not pictured in the screenshot. 
In the Undergarden dimension there are also two portals right next to eachother.

![image](https://user-images.githubusercontent.com/4461697/108612249-be073280-743a-11eb-8c61-b2fb070c0186.png)

**Comment by quek04** [comment] 2021-02-21 00:50
what version of forge are you using

**Comment by SodiumShine** [comment] 2021-02-21 00:54
Sorry, forgot to give all that.
Forge 36.0.14
Minecraft 1.16.5
Mod version 1.16.5 - 0.4.5

**Comment by quek04** [comment] 2021-02-21 18:36
ugh, i don't know why this is happening again. this was previously caused by POI data being messed up but that was fixed by a way older forge version

**Comment by quek04** [comment] 2021-02-21 18:39
i just tested the portal on forge 36.0.14 and it works fine

**Comment by Bidgam** [comment] 2021-02-21 20:18
You referred my issue to here as probably similar. I'm using Forge 36.0.15 and it occurs with this same version of the mod.

I noticed that when I returned from The Undergarden it would create the new portal I exited from and always about 20 blocks higher than the one I had initial entered in from (and a bit off on the X axis randomly too). I was also already high in the air for my base at about 180 blocks.

Perhaps the height compatibility needs adjusting? If there's anything else we can do to test.

**Comment by quek04** [comment] 2021-02-21 20:30
"height compatibility" isn't a thing

**Comment by Bidgam** [comment] 2021-02-21 20:30
> "height compatibility" isn't a thing

Ok, just giving out ideas. If it isn't a thing, then something else is of course going on.

**Comment by Bidgam** [comment] 2021-02-21 20:32
What about the portal being in proximity to other portals like the Nether portal, could that have an effect somehow?

**Comment by quek04** [comment] 2021-02-21 20:33
no

**Comment by Bidgam** [comment] 2021-02-21 20:41
Well, it happens all the time. I'll try to nail down the frequency and see if there's any axis differences on where it keeps generating the second portal.

What about use of Versatile Portals mod? https://www.curseforge.com/minecraft/mc-mods/versatile-portals

**Comment by PaperMold** [comment] 2021-02-25 02:10
Happens 100% of the time to me in Forge: 35.1.4
@quek04 is that normal on that forge version?

**Comment by quek04** [comment] 2021-02-25 02:11
@Axspeo Update Forge and make a new portal, the issue here is caused by something else

**Comment by Bidgam** [comment] 2021-02-25 02:43
> Happens 100% of the time to me in Forge: 35.1.4
> @quek04 is that normal on that forge version?

You might need to update later than 36.0.15 as I have that version and it still occurs. My instance could be caused by something else, but I don't have a clue as to what, so atm I'm a bit stuck either way.

**Comment by PaperMold** [comment] 2021-02-25 18:35
Forge: 36.0.42

It works just fine.

Guess this is not a real issue with undergarden then?

**Comment by Bidgam** [comment] 2021-02-26 02:36
Might not be, I'm trying a few things on my end. Might as well close this issue if yours is resolved. I'll create a new one if it warrants it in the future.

**Comment by pjlasl** [comment] 2021-02-28 22:27
I am also seeing this. I am on the lastest mod version and forge version

**Comment by pjlasl** [comment] 2021-03-01 14:45
Here is what I see in the console log:

****************** Blame Report 1.9.2 ******************
Failed to load structure nbt file from: undergarden:catacombs/way_pool
The path represented by this is: data/undergarden/structures/catacombs/way_pool.nbt
The calling Template Pool is: undergarden:catacombs/catacombs_tunnel6
Most common cause is that there is a typo in this path to the nbt file.
Please let the mod author know about this so they can double check to make sure the path is correct.
A common mistake is putting the structure nbt file in the asset folder when it needs to go in data/structures folder.

[INFO] .... [minecraft/DedicatedServer]: pablleaf has made the advancement [Birth Control]
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=76, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-193, y=76, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-193, y=75, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=75, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=74, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-193, y=74, z=76}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=76, z=74}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-191, y=76, z=74}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-191, y=75, z=74}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=75, z=74}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-192, y=74, z=74}
[ERROR] .... [minecraft/PointOfInterestData]: POI data mismatch: never registered at BlockPos{x=-191, y=74, z=74}
[INFO] .... [minecraft/DedicatedServer]: pablleaf has reached the goal [Half Heart Life]
[INFO] .... [minecraft/ServerPlayNetHandler]: pablleaf lost connection: Disconnected
[INFO] .... [minecraft/DedicatedServer]: pablleaf left the game

**Comment by PaperMold** [comment] 2021-03-01 16:44
> 
> 
> I am also seeing this. I am on the lastest mod version and forge version

Latest forge version aka 36.0.42?

**Comment by Tamaized** [comment] 2021-03-01 16:52
I've got enough information here to investigate and probably have found a solution

**Comment by pjlasl** [comment] 2021-03-01 18:56
My server is on 36.0.42, but in my single player 36.0.43...same thing happens

**Comment by quek04** [comment] 2021-03-26 14:22
I think I fixed this a while ago

**Closed as completed by quek04** 2021-03-26 14:22 UTC

**Comment by prenetic** [comment] 2021-06-09 04:20
Can you let us know which version this was fixed in?

We're running the `FTB Endeavor 1.4.0` modpack and this is an issue for us. Includes `The Undergarden 0.5.1` and `Forge 36.1.16`.
