### ISSUE TITLE
Portal not working

### ISSUE THREAD

**Issue by IDEZIHREE** [quek04/The-Undergarden#76] opened 2021-02-02 02:24 UTC
We start the portal and it lights but nothing happens when we get in it tried playing the 1.16.3 version and then Switched to 1.16.4 (says it works on 1.16.3) still no luck. Playing on forge 1.16.3

**Comment by quek04** [comment] 2021-02-02 02:25
what version of the Undergarden and Forge are you using?

**Comment by IDEZIHREE** [comment] 2021-02-02 02:28
Using forge 1.16.3 and under garden 1.16.4 0.3.8 we had the 0.3.7 first but that didn’t work so we tried switching it to 0.3.8 and still no luck

**Comment by quek04** [comment] 2021-02-02 02:28
you're quite a few versions behind - try using 0.4.5

**Comment by quek04** [comment] 2021-02-02 02:29
you should also update your forge too

**Comment by IDEZIHREE** [comment] 2021-02-02 02:29
Can I still use that with 1.16.3 server?

**Comment by quek04** [comment] 2021-02-02 02:30
yes, but there's no reason to not use 1.16.5

**Comment by IDEZIHREE** [comment] 2021-02-02 02:31
Okay I’ll try and see what I can do I just got into modded servers so not sure how to update my current server to a 1.16.5 forge but I’ll give it a try thanks

**Comment by IDEZIHREE** [comment] 2021-02-02 02:56
One more thing modded servers for 1.16.5 forge are kind of messed up right now a lot of people are having troubles making them is there any way it could work for 1.16.3 or no probably not

**Comment by quek04** [comment] 2021-02-02 15:42
wdym? 1.16.5 works fine for all the people I've played with

**Comment by quek04** [comment] 2021-02-02 15:42
whatever, I'm closing this - this is just an issue caused by you not updating

**Closed as completed by quek04** 2021-02-02 15:42 UTC
